services:
  proxy:
    image: vimagick/tinyproxy
    container_name: tinyproxy
    ports:
      - "8888:8888"
    volumes:
      - ./tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf
      - ./data:/var/log/tinyproxy
